global:
  datacenter: dc1
  image: "consul:1.7.0"
  imageK8S: "hashicorp/consul-k8s:0.11.0"

server:
  replicas: 1
  bootstrapExpect: 1

client:
  enabled: true
  grpc: true

ui:
  enabled: true

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  default: true

connectInject:
  enabled: true
  #envoy image with curl and utils
  imageEnvoy: nicholasjackson/consul-envoy:v1.7.0-v0.12.2

  #true will inject by default, otherwise requires annotation
  default: false

  centralConfig:
    enabled: true
    defaultProtocol: "http"
    proxyDefaults: |
      {
      "envoy_dogstatsd_url": "udp://127.0.0.1:9125"
      }

